### ISSUE TITLE
Điểm danh

### ISSUE THREAD

**Issue by HuuNghia10A12PhuNhuan** [HoangBao04/10A12-Nhom05#1]
Hữu Nghĩa

**Comment by HienCaoPhuNhuan** [comment]
@HoangBao04  chưa đủ thành viên nha con

**Comment by HoangBao04** [comment]
Dạ con thấy đủ rồi mà thầy, thầy coi lại dùm con


[cid:2d88eb50-65c9-4cf9-b9f3-08c774eb8715]

________________________________

**Comment by ThuyDung07-A12** [comment]
Thùy Dung

**Comment by Dangchauu** [comment]
Quỳnh Châu
