### ISSUE TITLE
Bàn luận về câu 4

### ISSUE THREAD

**Issue by DuyHieu14-10A12** [HoangBao04/10A12-Nhom05#12]
@HoangBao04 @HuuNghia10A12PhuNhuan @ThuyDung07-A12 @Dangchauu bàn luận giúp @HoangBao04 ở đây nha

**Comment by HuuNghia10A12PhuNhuan** [comment]
![image](https://user-images.githubusercontent.com/92022929/138289324-1cf2eda2-e1de-4e18-9a41-37b666d0120c.png)
đây là bài mà t đã làm, mọi người có đóng góp ý kiến gì ko?
