### ISSUE TITLE
phân chia công việc bài 5 + 6

### ISSUE THREAD

**Issue by HuuNghia10A12PhuNhuan** [HoangBao04/10A12-Nhom05#13]
![image](https://user-images.githubusercontent.com/92022929/140254340-36340379-7e69-4dde-9ec4-26ea1135d253.png)
* mỗi người một câu, người còn lại sẽ làm file word.
* cách chọn như cũ, chỉ khác là giờ có thêm lựa chọn: làm file word và không cần TL câu hỏi

**Comment by Dangchauu** [comment]
Tui chọn câu 1 nha

**Comment by HoangBao04** [comment]
tui cau 2 nhoe'

**Comment by ThuyDung07-A12** [comment]
tui câu 4 nha

**Comment by DuyHieu14-10A12** [comment]
tui cau 3 nhoe

**Comment by HuuNghia10A12PhuNhuan** [comment]
thế t làm file word.
* mọi người cần trợ giúp gì cứ báo t nha.

**Comment by ThuyDung07-A12** [comment]
Hiếu làm câu 3 nhớ gửi tui ví dụ để tiện làm câu 4 nha

**Comment by DuyHieu14-10A12** [comment]
> Hiếu làm câu 3 nhớ gửi tui ví dụ để tiện làm câu 4 nha

ukie @ThuyDung07-A12
