### ISSUE TITLE
Vấn đề câu 3

### ISSUE THREAD

**Issue by HuuNghia10A12PhuNhuan** [HoangBao04/10A12-Nhom05#14]
![image](https://user-images.githubusercontent.com/92022929/140613080-0338af7f-5026-440d-b073-03c93b0bec04.png)
**Phần "2 cái vd" của câu 3 chưa đc hiểu rõ.**

**Comment by DuyHieu14-10A12** [comment]
@HienCaoPhuNhuan thầy ơi cái phần ví dụ câu 3 là mình đưa ví dụ về cái gì vậy thầy ? Là đưa vdu về việc giải toán trên máy giống 100% so với việc giải quyết vấn đề ngoài đời đúng khgo6ng ạ? Với lại là trong ví dụ mình có cần nêu ra các bước giải quyết của vấn đề mình ví dụ không thầyyy

**Comment by HienCaoPhuNhuan** [comment]
> @HienCaoPhuNhuan thầy ơi cái phần ví dụ câu 3 là mình đưa ví dụ về cái gì vậy thầy ? Là đưa vdu về việc giải toán trên máy giống 100% so với việc giải quyết vấn đề ngoài đời đúng khgo6ng ạ? Với lại là trong ví dụ mình có cần nêu ra các bước giải quyết của vấn đề mình ví dụ không thầyyy

Đúng rồi
Các bước là dành cho câu cuối

**Comment by DuyHieu14-10A12** [comment]
à dạ là mình chỉ cần đưa 

> > @HienCaoPhuNhuan thầy ơi cái phần ví dụ câu 3 là mình đưa ví dụ về cái gì vậy thầy ? Là đưa vdu về việc giải toán trên máy giống 100% so với việc giải quyết vấn đề ngoài đời đúng khgo6ng ạ? Với lại là trong ví dụ mình có cần nêu ra các bước giải quyết của vấn đề mình ví dụ không thầyyy
> 
> Đúng rồi Các bước là dành cho câu cuối

à dạ con cảm ơn thầy

**Comment by DuyHieu14-10A12** [comment]
@ThuyDung07-A12 cái ví dụ nè nha : 
+ Đưa con robot ảo đi đến điểm cần thiết 
+ Giải 1 bài toán bậc nhất 1 ẩn
