### ISSUE TITLE
Phân chia công việc bài 7+8

### ISSUE THREAD

**Issue by ThuyDung07-A12** [HoangBao04/10A12-Nhom05#15]
![image](https://user-images.githubusercontent.com/92025745/141682519-9fdb9d7e-16c7-4c1e-9a50-f97f67ce5fe9.png)
 .1 người làm 2 câu
 .1 người làm 1 câu + file word
 . 3 người làm 1 câu

**Comment by ThuyDung07-A12** [comment]
tui làm câu 3 nha

**Comment by DuyHieu14-10A12** [comment]
@HienCaoPhuNhuan thầy ơi cho con hỏi là câu 3 bài 8 là ai cũng làm hết phải không ạ?

**Comment by DuyHieu14-10A12** [comment]
tui làm câu 1 bài 8 với câu 3 bài 8 nha

**Comment by HienCaoPhuNhuan** [comment]
> @HienCaoPhuNhuan thầy ơi cho con hỏi là câu 3 bài 8 là ai cũng làm hết phải không ạ?

Tùy ý mấy đứa

**Comment by Dangchauu** [comment]
Tui làm câu 1 bài 7 nha

**Comment by DuyHieu14-10A12** [comment]
> > @HienCaoPhuNhuan thầy ơi cho con hỏi là câu 3 bài 8 là ai cũng làm hết phải không ạ?
> 
> Tùy ý mấy đứa

dạ thầyy

**Comment by HoangBao04** [comment]
tui làm câu 2 bài 8 nhaa

**Comment by HuuNghia10A12PhuNhuan** [comment]
vậy t làm câu 2 bài 7 và làm file word
