### ISSUE TITLE
Phân chia công việc bài 9+10

### ISSUE THREAD

**Issue by DuyHieu14-10A12** [HoangBao04/10A12-Nhom05#16]
![image](https://user-images.githubusercontent.com/92068009/142726613-d813f6ae-61c7-4ee9-becb-8a3715cfe508.png)

**Comment by HoangBao04** [comment]
Tui làm câu 1 bài 10 nhaaa

**Comment by HuuNghia10A12PhuNhuan** [comment]
> Tui làm câu 1 bài 10 nhaaa
ok

**Comment by HuuNghia10A12PhuNhuan** [comment]
> Tui làm câu 1 bài 10 nhaaa

ok

**Comment by HoangBao04** [comment]
tui tạo project luôn rồi mng tranh thủ chọn câu để làm rồi để vô đó cho Nghĩa làm file word nhaaa <3

**Comment by Dangchauu** [comment]
Tui làm câu 2 bài 10 nha

**Comment by HuuNghia10A12PhuNhuan** [comment]
> Tui làm câu 2 bài 10 nha

ok

**Comment by ThuyDung07-A12** [comment]
tui làm câu 1 bài 9 nha

**Comment by HuuNghia10A12PhuNhuan** [comment]
> tui làm câu 1 bài 9 nha

ok

**Comment by DuyHieu14-10A12** [comment]
tui câu 3 bài 9 nha

**Comment by HuuNghia10A12PhuNhuan** [comment]
> tui câu 3 bài 9 nha

ok

**Comment by HuuNghia10A12PhuNhuan** [comment]
vậy tui câu 2 bài 9
